In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split,ShuffleSplit,StratifiedShuffleSplit,KFold,cross_validate
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [33]:
df=pd.read_csv(r"C:\Users\jyoti\Downloads\advertising.xls")
df

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Male,Country,Timestamp,Clicked on Ad
0,68.95,35,61833.90,256.09,Cloned 5thgeneration orchestration,Wrightburgh,0,Tunisia,27-03-2016 00:53,0
1,80.23,31,68441.85,193.77,Monitored national standardization,West Jodi,1,Nauru,04-04-2016 01:39,0
2,69.47,26,59785.94,236.50,Organic bottom-line service-desk,Davidton,0,San Marino,13-03-2016 20:35,0
3,74.15,29,54806.18,245.89,Triple-buffered reciprocal time-frame,West Terrifurt,1,Italy,10-01-2016 02:31,0
4,68.37,35,73889.99,225.58,Robust logistical utilization,South Manuel,0,Iceland,03-06-2016 03:36,0
...,...,...,...,...,...,...,...,...,...,...
995,72.97,30,71384.57,208.58,Fundamental modular algorithm,Duffystad,1,Lebanon,11-02-2016 21:49,1
996,51.30,45,67782.17,134.42,Grass-roots cohesive monitoring,New Darlene,1,Bosnia and Herzegovina,22-04-2016 02:07,1
997,51.63,51,42415.72,120.37,Expanded intangible solution,South Jessica,1,Mongolia,01-02-2016 17:24,1
998,55.55,19,41920.79,187.95,Proactive bandwidth-monitored policy,West Steven,0,Guatemala,24-03-2016 02:35,0
999,45.01,26,29875.80,178.35,Virtual 5thgeneration emulation,Ronniemouth,0,Brazil,03-06-2016 21:43,1

In [34]:
df.shape

(1000, 10)

In [35]:
df.head()

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Male,Country,Timestamp,Clicked on Ad
0,68.95,35,61833.90,256.09,Cloned 5thgeneration orchestration,Wrightburgh,0,Tunisia,27-03-2016 00:53,0
1,80.23,31,68441.85,193.77,Monitored national standardization,West Jodi,1,Nauru,04-04-2016 01:39,0
2,69.47,26,59785.94,236.50,Organic bottom-line service-desk,Davidton,0,San Marino,13-03-2016 20:35,0
3,74.15,29,54806.18,245.89,Triple-buffered reciprocal time-frame,West Terrifurt,1,Italy,10-01-2016 02:31,0
4,68.37,35,73889.99,225.58,Robust logistical utilization,South Manuel,0,Iceland,03-06-2016 03:36,0

In [36]:
##Duplicates
df.duplicated().sum()

np.int64(0)

In [37]:
df.drop_duplicates(ignore_index=True,inplace=True)

In [38]:
df.duplicated().sum()

np.int64(0)

In [39]:
###info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Daily Time Spent on Site  1000 non-null   float64
 1   Age                       1000 non-null   int64
 2   Area Income               1000 non-null   float64
 3   Daily Internet Usage      1000 non-null   float64
 4   Ad Topic Line             1000 non-null   str
 5   City                      1000 non-null   str
 6   Male                      1000 non-null   int64
 7   Country                   1000 non-null   str
 8   Timestamp                 1000 non-null   str
 9   Clicked on Ad             1000 non-null   int64
dtypes: float64(3), int64(3), str(4)
memory usage: 78.3 KB

In [40]:
df.columns

Index(['Daily Time Spent on Site', 'Age', 'Area Income',
       'Daily Internet Usage', 'Ad Topic Line', 'City', 'Male', 'Country',
       'Timestamp', 'Clicked on Ad'],
      dtype='str')

In [41]:
features=df[['Daily Time Spent on Site','Age','Area Income','Daily Internet Usage','Male']]
features.head()

   Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  Male
0                     68.95   35     61833.90                256.09     0
1                     80.23   31     68441.85                193.77     1
2                     69.47   26     59785.94                236.50     0
3                     74.15   29     54806.18                245.89     1
4                     68.37   35     73889.99                225.58     0

In [42]:
target=df[['Clicked on Ad']]

In [43]:
features.boxplot()

In [44]:
from sklearn.feature_selection import f_classif

f_clas= f_classif(features,target)

pd.Series(f_clas[0],index=features.columns).sort_values(ascending=False)

Daily Internet Usage        1618.976456
Daily Time Spent on Site    1268.525161
Age                          319.643165
Area Income                  292.770617
Male                           1.445286
dtype: float64

In [45]:
features.drop(columns=['Male'],inplace=True)

In [46]:
features.head()

   Daily Time Spent on Site  Age  Area Income  Daily Internet Usage
0                     68.95   35     61833.90                256.09
1                     80.23   31     68441.85                193.77
2                     69.47   26     59785.94                236.50
3                     74.15   29     54806.18                245.89
4                     68.37   35     73889.99                225.58

##Hold Out Method

In [67]:
###Train_Test_split
x_train,x_test,y_train,y_test=train_test_split(features,target,train_size=0.8,random_state=100,stratify=df['Clicked on Ad'])

print(x_train.shape)

print(x_test.shape)

print(y_train.shape)

print(y_test.shape)

(800, 4)
(200, 4)
(800, 1)
(200, 1)

In [68]:
std_sca= StandardScaler()

x_train= pd.DataFrame(std_sca.fit_transform(x_train),columns=x_train.columns)

x_test= pd.DataFrame(std_sca.transform(x_test),columns=x_test.columns)

In [69]:
x_train.head()

   Daily Time Spent on Site       Age  Area Income  Daily Internet Usage
0                  1.189623  0.236961    -0.288424              1.483000
1                 -0.888752  1.153304     0.209589             -1.395667
2                 -0.531947  1.496933    -0.078415             -1.498419
3                 -1.338314 -0.793926    -0.292672             -0.850414
4                  0.968243 -1.023012     0.521674              0.641904

In [70]:
log_model= LogisticRegression()

log_model.fit(x_train,y_train)

#### Training Validation

y_pred= log_model.predict(x_train)

train_acc= accuracy_score(y_train,y_pred)

### Testing validation

y_pred1= log_model.predict(x_test)

test_acc= accuracy_score(y_test,y_pred1)

print('Training_Acc:',train_acc,',','Testing_Acc:',test_acc)

Training_Acc: 0.9675 , Testing_Acc: 0.975

###Suffle Split

In [71]:
shuf_split=ShuffleSplit(n_splits=10,test_size=0.2,random_state=50)

for train_split, test_split in shuf_split.split(features,target):

    print(train_split,test_split)

[886 488 265 112 650 577 280 571 629 158 668 869 983 944 715 232 146 558
 586 356 482 126 213 315 481 293 573 491 806 648  43 286 728 861 370 407
 722 423  18 588   9 339 484 124 713 880 862 366 483 255 651 492 210 220
 458 719 479  25 696 188 535 192 379 279 305 159  35 599 879 560 626 191
 443 382 203 955 845 943 591 267 162 274 527 916 672 816 689 679 508 569
 270 598 982 538 206 472 115  42 383 257 788 579 554 882  44   8 494 935
 914 111 374 513 814 216 627 553 739 940 180 589 246 897 408 829 761 399
 108 770 855  87 345 323 168 758 110 638  94 945 828 902 503 789 259  23
 600  85 532 628 114 608 319 611 347 542  34 120 913 537 714 473 870 172
 999 337 100 442 353 653 496 195 746 227 468 201 287 500 718 821 470 805
  52 445  54 667  81 737 885 568 766 942 708 454 546 137 179 961 645 467
 273 143 151 624 849 354 485 175 534 691 317  24 670  80 294 682 324 145
 853 971 641 927 103 329 593 249 911 793 149 637  65 212 282 350 390 150
 214 890   1 424 973 734 977 803 295 767  14 204 182 181  89 830 817 148
 515 389 361 968 979 510 141 975 631 896 954 303 867 135  97 123 376 842
  67  83 664 281 660 919 884 208 920 238 840 387 570 444 476 552 223 895
 800 652 738 602 705 969 904 957 298 170 610 102 493 322 372 735 680 692
 505 557 781 946 987 268 236 871 397 567 930 702 138 438 639 432 950 422
 769 136 865  15 290  88 307   6 856 607 980 512 461 892   3 549 247 555
 107 272 377 140 200 302 187 985  72 219 121 662 776 785 802 654 962 177
 760 687 487 292 640 276 190 852 891 574 784  75 690 465 437 525 380 772
 490 457 299  20 355 674 846 543 420 391 185 581 547 813  47 796 958 283
 409  63 632 801 837 967 820 731 405 858 430 198  74 119 521 723 663 360
  55 709 400 773 996 601 717 511 338 562 556 516 335 392  61 780  84  73
 720 838 325 698 615 113 226 306 378 792 893 874 756 822  33 349 912 921
 825 832 928 429 477 905 673 153 839 635 938 199 768 266 231 304 889 576
 230 647 597 269 271 242 165 251 620 658 753 617 646 649 522 578 936  49
 863 733  39 167 384 710 676 531 782 903 184 786 122  41 215 995 207 697
 209 584 694 217 161 449 261 450  22 625 671 466 447 634 169 621  59 434
 196 544 915 310 595 545 301 924 899 533  53 375  96 332 357  12 765 686
 966 910 129 178 748 235  69 318 732 707 877 431  40 736 685 695 410 125
 843 729 878 373  60 327 352 362 296 428 864 894 495 712 809 988 262 506
 888 239 205 807 661 435 348  21 501 566 245 228 764 539 681 644 699  28
 751 462 241 176 963 848  78 311 189 580 173 956 564 334 965 925 887 406
 616 986 440 142 857 630  13 677 193 683 993 976 240 497 823 592  58  64
 393 254  57 804 233  30 933 906 117 346 526 876 960 587 762 498  56 256
 790 351 847 824 994 451 426 277 131 675 900 425 519 827 411 155 779 934
 456 730  17 810 623 402 388  68 815 312 381 439 436 984 517 655 415 504
 923 818  27 486 291 171 812 446 798 872 224 275 941 342   4 590 309 300
  36 340 164 833 774  92 197 509 559 787 288 343 101 427 308 797 777 701
 385 211  45 826 403 704 972 186 128 740 548 711 909  62 174  91 152 156
  51 583 666 926 139 948 606 221  93   0 947 622 778 130 835 834 371 572
  26 499 419 105 414  79 642 147 518 507 320 937 106 341 561 799 811 404
 134 218 154 603 860 163 974 452 367  71 250  95 258 133 749 278 992 229
  70 132 990 289 109 907 480 688] [316 459 854  11 978 727 771 563 541 747 881 502 684 421 260 460 665 386
 636 401 757 412 643 725 478 693 612 248 866 234 523 952 575 922 931 263
 413 524 939 358 398 678 754 244 970 489 225 932 859  19 841 721 529 851
 194 619 998  90 898 949 918 775 883 202 395 755  29 752 104   7 363 929
 326 285 763 614 794  31 716 656 808 328 330 964 474 743 540 243 585 951
 536   2 253 953 463 745 441 991 396 795 528  10 321 657 368 831 724 989
 582 609 917 700 618 997 844 633  48 530 791 520 416 908 284 359 514 750
  16 127  82   5 314 364  50 850 166 116 433 550 237 594  32  66 659 365
 418 464 453 417  76 726 264 469 144 901 331  98 313 455 873 369  86 669
 336 471 783 118 475 959 703 706 875  99 297 605 565  77 222  46 759 819
 183 742 613 448 741 394 836 551 160 604 744 868 252 596 344  37 981  38
 333 157]
[826  15  58 814 159 381 841 500 809  87  10 578 883 487 944 467 979 892
 358 691 362 328 828 996 785  16 235 758 555 726 804 719 386 817 696 254
 924 303  24 741 598 766 998 126 209 736 410 670 656 668   8 374  82 152
 997 870 825 802 740  52  17 942 567 975 165 693 246 746 299 861 620  49
 338 721 275 429 110 132 703  98 663 493 709 764 774 647 147 673 530 762
 264 743 501 862 589 730 492 895 491  47 679 259 334 518 347 384 638 808
 562 452 750 249 551 822 160 569 560 848  72 380 242 742 485 674 650 587
 912 267 731  26  59 397 361 225 473 952 375 297 903 298 364 311 403  67
  28 405 577 204 542 911 435 453 843 548 119 417 950 624 131 813 827  42
 959 876 265 851 428 456 115 724 846 522 836 554 660 863 305 526 436 162
 294 980 946 158 662 613 800 484 233 245 711 938 854  69 655 430 565 421
 437  71 287 185 868 148 496 988  38 882 901 124 913 738 965 915 506 339
  32 111 286  99 794 354 474 608 925 787 897 962  35 382 238 116 444 366
 468 345 602 971 105 793 867 680 457 775 227 401 631  91 777   6 916 735
 120 415 791 654 739 595 694 625 171  36 593 274   9 545 442  18 478 780
 659 898 377 379 657 434  96 768  19 313 652  73 359 833 860 243  23 585
 407 161 563 349 129 579 524  56 507 866 198 184  46 546 707 708 440 216
 212  83 889 192 445 669  95 881  77 664 237 497 995 628 853 963 727  84
 641 256 255 592  33  41 333 175 176 215 179 918 155 689 138 139  40 799
 329 202 910 106 180 218 344 782 536 172 633 844 544 949   7 581 312 705
 281 104 196 284 734 823 686 572 332 308 521 999 745  25 330 688 455  60
 627 558 993 552 466 464 118 385 293 917 681 983 547 480  86 795 982 990
 890 564 309 450 102 637 137 978 849  76 357 350 715 257 754 954 262 805
 390 646 322 926 188 899 153 230 984 519 363 409 947 931 894 523  93 490
 207 835 973 767 991 607 700 590 992 183 781 584 411 622 125 885 692 277
 424 396 316 958 414 340 402 513 295  50 261 508 398 816 181 319  79 495
 723 355 187 676 811 315 900 765 747 936 103 251 260 190 321 801 502 310
 824 832 588  64 272 247 778 586 296 465  94 232   1 244 645 684 182 412
 725 955 744 317 789 438 372 449 482 600 616 543 177 905 166 699 306  12
 114 320 612 503 772  37 698 713 419  78 520 930 771 702 933  97 850  57
 541 394 483 571 869 957 471 488 948 803 720 712 395 539 443 133 626 632
 369 276 935 921  54 228 549 206 634 481 609 893 512 373 220 855  34 346
 840 258 477 751 226 752 972 574 798 376 872 878 331 635 960 266 360 845
 597 685 416 941 193 494   4 304 282 213 489 902 342 761 594 976 810 136
 498 439 408 178 943 559 884  51 596 479 642 922 234 324 576 550 749 109
 224 875 830 141 378 605 934 389 130 117 796  39 189   3 348 981  31 154
 197 431 336 682 422 658 557 476 446 820 553 511 704 636  65 231 599 951
 651 173  30 932 653 614 367 604  13 516 755 591 420 217  70 200 101 391
 756 135 757 538 100 909 906 677 469 203 788 461  74  45 201 665 649 675
 989 759 648 534 280 531 886 142 325 164 406 510 621 687 966 985 575 732
 717 229 821 871 459 326 639 919 773 236 250 753 289 701 432 302  61 769
 748 451  11 784 834 300 418  85 779 671  44 783 157 122 151 706   2 112
  75 857 460 505 454 290 603 661 728 514 169 383 351 194 145 904 678 812
 108  43 714 970 986 838 617 515 573 683 291 529 427 937 413 223 140 968
 792 879 472 205 365 710 301 113] [ 20 123  89 441 168 718 928 423 880 241 134 426 279 447 199 610 907 568
 458  68 667 128 252 819 940 352 858 643 269 770 341 695 831  81 463 583
  66 475 945 195 837 327 121 404 760 371 425 323 107 540 163 167  92 763
 859 288  55 353 615 368 278 877 268 486 570 856 623 790  21 400 239 525
 961 214 847 337 143 619 908 149 582 208 240 815 920 797 874 618   0 994
 697 127 929 537 388 818 273  27 786 865 270 174 927 644 263 923 219  29
 839 630 672 527 956 601 977 733 533 532 561  80 842 283 292 144 939 737
 891 191 248 150 504 186 887  62 580 729 253 974 221 722 318 640 852 969
 343  63 566 211 807 953 433 170 914 829 987  90 864 392 606 716 509 314
  14 470 370 156 896 888 210  53 387 335 556 776 393  48 611 666 307 271
  22 399 448 222 964 535 462   5 629 528 690 356 873 285  88 146 967 806
 517 499]
[466 750 288 604 802 220 630 884 934  65 840  50 571 913 972 341 728 853
 814 496 803 818 906 520  67 878 381 754 665 271 795 476 208 410 980 386
 953 642 581 996 369 229 166 680 551 509 177 791 515 950 258 713 866 689
  58 424 179  71 439 372 768 929 699 464  90 150 695 567 815 778  25 114
 871 444 260   5 396 942 720 663 455 525 743  32 289 195 376 988 259 887
   0 582 917 974 125 613 973 584 708 514 116 621 363 165 648 182 305  48
 489 477 794 119 914 749 501 318 635 655 730 714  77 771 820 668 892 513
 358 552 955  29 957 406 852 744 631 159 733 956  94  55  66 798 528 745
 672 748 554 656 762 821 832 175 347 223 910 986 301  52 462 500 465 419
 502 894 997  56 600 393 854 706 530 580 495 676 510 756  97 734 313 101
 171 218 275  23 420 344 925 511 924 124 326 317 559 999 248 379 579 191
 838  78 911  10 822 425 979 662 595 370 206 540 597 599 549 826 522 104
 533 526 732 712 269 529 836 591 940 454  63 716 100 157 207 965 828 330
 264 335 268 747 442 323 178 697 483 578 315 981 594 947 886 574 788  98
 299 270 431 667 784 833 217 970 383 460 458  47 414 703 311 302 374  88
 895 423 353 371 156 137 792 373 932 982 958 312 806 678 519 718 936 773
   7 548 856 900 786 355  15 707 153 659 983  99 129 823 901  83  19 738
 192 576  76 286 310 629 284 991 278 864 577 872 226 566 238 763 669 919
 585 968 937 546   1 401 418 121 767 811 964 199 700 251 813 711 693 487
 298 254  60 436 412 737 608 295 430 160 948 657 758 735 451 319 839 314
 422 343 705 280 403 142 516 250  28 184 337 563 592 859  86 193 472 810
 445 491 346 143  49 624 219 378 285 247 202 345  95 921 951 534 211 846
 237 639 485 146 212 531 266 470 848  57 960 521 255 325 834 596 797 402
 187 688 638 267 770 122 151 274 300  37 172 632 128   6 493 252 517 780
 113 855 480 654 679 829 976 282 499 830 408 281 994 677 850 949 868 505
 174  30  17 907 473 849 152 918 790 715 204 189 279 664  31 909 523 364
  42 240 640 675 263 694 214 361 593 757 198 228 457 779 612 761 141 134
 928  14  20 772 446 627 709 391 904 564 601 935 131 725 740  53 874 684
 561 766 589 550 945 896 449 782 167  68   4 429 879 488 382 541 681 883
 196 641 287 569 367 962 539  35 739 824 316 783 362 623 109 686 392 357
 644  74  87 277 610 793 321 873 126  43 993 905 764 322 416 741  51 494
 421 851 399 484 903 469  45 807 261 933 120 565 508 290  80 144  96 262
 253 139 249 232 809 474 467 776  22 273 197 448  81 107 863 661 890 304
 637  39  46 180 967 338 691 234 200 542 506 297 225 825 568 765 572 405
 625 975 482  73  11 723  59 397 400 256 245 865 835 978 154 943 351  93
 348 602 643 145 805 781 722 670 360 673 800 961  64 987 915 518 224 395
 450 636  82 682 471  92 292 537 265 411 303 916  40 692 837 456 463 908
 434 352 753 959 328 719 398 727 724 598 481  44 742 923 618 333 498 880
 586 105 590 127 404 938 760 385 816 683 626 558 492 438 103 628 543 611
  34 573 320 666 777 294 651 544 889 583 115 535 428 133 375 717 845 861
 213 334 239 188 881  89 475 674 380 390 877 804 205  70  13 615 843 857
 329 726 327 954  84 944 194  61 244 336 354  72 547 308 140 862 897  27
 587 605 427 413 731 985 296 867 536 359 497 603 941 242 930 110 389 272
 620   2  62 461 946 394 331 108 658 538 990 992 799 117  38 350 173  21
 365 164 185 952 969 876 617 545] [215 162 671 209 201 995 210 902 437  33 729 435 387 478 176 963 560 339
  26 233 388 888  79 230 796 276 377 161 702 111 841 847  91 736 920 507
 168 527 607  36 222 801 819 989 349 817 998 356 106 922 512 332 440 557
 622  12 769 227 130 283 774 441 163  16 653 971 118 687 701 503 685 181
 870 698 588 710 660 532 407 170 898 243 775 562 844 555 340 646  24 696
 246 759 619 366 479 468  69 885 645 149 236 869 490   9 652 216 755 556
 614 148 447 102 190   3 575 432 342 426 486   8 787 433 704 324 606 221
 453 789 721 912 183 123 147 570 808 203 633 927 650 459 553 649 842 926
 241 138 504  41 984 752 309 415 452 746 751 293 893 186 409 939 858 135
 875 860 306 235 647 785 307 690 155 634 368  54 158 616 136 812 827  75
  85  18 231 384 257 891 417 831 966 931 609 132 443 882 112 899 169 524
 291 977]
[ 85 776 764 953 384 601 934 876 611 481 615 784  81 243 190  21 452 649
 716 757 442 537 572 983 802  70 446 770 717   8 128 963 672   6 630 305
 395 385 596 930 890 940 233 307 992 273 879 853  40 519  25 767 408 845
 809 886 945 109 891 153 980 645 863 462 112 387 662 292 484 901 842 648
 147 142 441  36 340 164 651 154  23 467 251  95 620 855 691 641  30 548
 478 487  20 177 488 412 865 921  16 388 124 579 202 551 366 399 285 510
 787 220 539 402   7 293 678 830 448 512 432 234 972 557 389 907  45  91
 479 415 925 110 547  64 805 692 227 916 204 552 297 300  39 753 781 195
 325 946 196 771 987 590 411 778 259 887 309 697 993 719 889 326 380 573
 588 985 332 825 711 742 119  26 701 824 509  94 851 931 989 687 897 949
  17 729 474 713 657 419 315 870 932  42 508 180  77 878 532 658 734 685
 982 600  11 756 403  67  69 609 643 477 214 295 966 569 943 188 283 133
 417  84 667 360 222 345 212 132 749 455 951 589 513 926 852 149 524  65
 688 775 505 739 469 594 278 379 279 917 875 280 862 910 631 741 738 731
 118  82 690 804 504 844 779 171 287 375  88 801 960  18 284 636 996 358
 874 623 562 350 785 884 924 117 201 973 351  78 550 906 371 364 466 200
 494 141 895 566 511 501 633 893 744 331 252 859 203 249 304 660 595  51
 823 988 357 367  80 299 978 898 612 587 790 941 329 336 793  14 436 286
 435 337 438 480 773 602 290 301 695 654  83 724 291  22 563 998 606 122
  76  31 647 276 298 472 354 522 740 269 156  96 683 206 439 306 518 476
 827 812 810 217 456 621 575 465 986 567 999 148 608 829 198 179 885 693
  66 144  89 653 239 839 915 894  93 791 146 376 335 136 378 881 120 599
 145 712 507 355 528 416 905 503 394 570 848 104 362 833 334  57 617  15
 927 864 468 857 670 637   4 696 888 991 398 383 841 679 743 735 880 170
 942 545 840 410 979  71 736 221 995 699 342  53 207  54 266 235 718  74
 803 314 451 173 192 956 591 393 270 323 639 745  52 646 834 352   5 883
 216 121 502 614 386 896 397 333  38 929 546 860 426 372 912 228 758 950
 262 485 162 444 140 899 707 635 807 682 348 219 675 818 390 258 709 229
 178 116 175 499  63 523 459  37 310 463 856 858 143 674 491 777  50 933
 421 324 430 663 420 748 913 396 339 274 126  44 135 846 694 492 224 294
 944 656 313 540 627 750   0 826 263 470 231 920  10 850 500 105 255 559
 788 431 328 919 312 271 199 892 138 247 527 628 127 765 213 490 131 769
 108 157 669 974 700 114 529 450 427 780 429 638 747 275 349 316 650 514
 158 975 482 732 684 223 720 311 585 659  27 625 971 318 525 577 811 814
 867 242 967 174 843 789 320 774 957 762  92 102 169 423  32 882 597  43
 125 586 343 766 837 193 197 183 240 936 911 516 272 990 644 382   2 347
 984 161 768 184 418 106 257 406 377 248 664 755 618 150 613 576 530 903
 277 726 808 454 728 434 473 962 877 580 725 854 759 368 969 935   9 605
 303 640 181 604 838 792 139  55 428 245 832 445 327 414 341 970 361   1
 583 822 798 558 381 866 836 111 194 238 191 939 400 918 806 209 723 902
 457 702 714 565 796 534 554 676 655 642 346 288  29 556 704  33 581 437
 497  97 489 964 115 760 264 520 668 483 515 610 733 661 495 544 592 861
  24 574  34 449 208 958 607 392 391 813 815 373 189 409 782 959 603 246
 182  72 103 634 107 166 873 665 730  35 555  62 447  46 498  98 541  60
 422 797   3 819 475 433 869 296] [506 282  73 772 155 215  13 706 626 533 938 549 622 471 404 968 176 253
 737 673 561 619 538 727 680  75 267 629 904 783 598 817 113 652 593 244
 321 560 413 123 847 281 703 578 952  47 872 553  58 795 165 460 369 976
  68 486 681 831 401 746 172  12 424 624 786 353 564 571 101 160 937 821
  90 260 954 914 908 344 535 828 185 130 250 531 526 359 356 232 543 440
 268 868 168 241  86 187 151 871 754 521 698 710 163 761 947 225 289  28
 330 365 363 763 265 708 453  61 458 849 616 705 955 794 689 715 721 997
 671 909 129 722 159 256 948 317 632 152 226 582 370 686 493 322 800 666
 218 210  79 496 517 751 799 584 536 923 405 100 568 211  48 230 186 236
 205 302  59 922 461 994  41 835 134  56 261 820 816 965 752 137 319 308
 981 425 443  19 407 928 961  99 677 167 254 464  87 338 542 374 900 977
 237  49]
[121 330 312 699 231 722 429 637 947 404 960 730 293 922 120 406 844 872
 859 366 874 525 565 323 512 899 462 182 414 941 336 853 799 151 307 751
 933 459 473 823 593  49 308 193 854 576  27   1 202 541 409 441 251 588
 945 219 921 199 178 259 402 624 771 656 511 856 666 538 750 144 948 830
 607 817 489 708 678 314 804 647 212 143 478 305 703 965 864 112 349 517
 762  64 469 879 361 689 837 581  60 732  77 355 673 980 892 388 108 208
 795 164 451 340 935 142 785 285 516 650 903  66 519 756 152 832 424 777
 333 688 937 743 665 204 790  17 599 483 270 229  46 325 994 975 934 835
 238 990 444 397 560  88 163 712 836 419 841 507 704  24 815 570 347 171
  25 520  18 669 170 827 757 566 191 166 641 185  70 454 290 962 608 156
 223 158 642 651 557 617  43 217 485   5 728 410 591 792 443 884 577 239
 943 257 123 860 475 449 716 769  16 528 881  26 242 197 433 245 500 988
 961 110 357 798 791 582 580 720 996 237 154 247 929  45 955 515 880 997
 513 904 213 866 407 401 494 445 680  34 631  91 140 405 256 214  89 636
 875  11  85 348 982 230 379 423  13 987 687  71 770 748 612 145 721 391
 390   6  29 611 848 602 286 509 646 979 867 403 749 253 435 592 697 221
 493  41 324 131 544 683 640 552  44 292 677 908 264 786 216 280 299 811
 400 865 905 809 487 897 465 931 731 654 362 911 411  67 989 670 194 399
 502 335   2 481 296  78  20 490  90 626 658 896 898 303 964 781  12 524
  62 482 233 660 973 562 334 595 440 663 207 547 783 598 852  74 727 648
 359   4 533 227 476 861 745 101 893 553 105 261  87 963 900 269 968 179
 690 682 572  52 909 321  86 585 474  30 415 706 907 644 240 698 605 726
 558 569  76 796 232 705 885 222 224  92   7  59 371 496 447 759  38 782
 747 828 252 439 776 713  37 619 813 260 614 463 754 273 364 821 977 555
 950 328 763 878  57 466 386 939 375 368 385 843 936 276 675 871 281 313
 839 192 417  68 236 546 228  32  33 752 521 877 559 606 319 634 460 976
 535 586   3 480  23 684 983 890 272 250 715 365 993 764 807 246  81 111
 186 119 610 649 659 339 177 778 457 153 787 309 895 497 857 632 883 916
 816   9 128 294 918 539 788 377 550 200 329  53 736 532 568 358 915  84
 346 805 981 255 477 719 986  48 755 638 573 318 471  15 812 639 537  10
 847  19  36 620 504  95 932 652 906 643 327 436 850 416 132 767 243 218
 295 135 765 579 891 278  69 551 332 629 574 635 995 793 370 117 126 298
 627 734 501 753 184 130 590 147 886 427 263 372 701  50 450 159 924 774
  28 383 888 695 740 107 522 851 810 761 696 291 622 849 597 174  98 978
 671 248  54 345 161 317 338 889 873 645 772 760 938 455 198 235 985  73
 738 518 667 138 882 209 833 710 876 267 133 322 148  58  56 700 718 870
 421 609 800 554 387  63 284  39 571 949 711 418 467 584 842 398  22 780
 434 122 155 779 136 495 564 374 157 674 514 472 940 902 970 928 623 668
 803 393 360 103 413  47 531 717 262 452  94 412 115 838 201 845 277 342
 912 160 868 746 488 304 814 508 479 331 594 492 187 530 458 211  31 464
 789 601 984 920 505 422 526 396 930 373 337 353 176 446 725 438 265  65
 946 587 215 603  35 741 376 536 254 840 919 681 664  79 249 351 543 289
 621 775 527 109 529 615 653 913  96 510 486 826 470 733 758 382 863 567
 310 425 819 380 266 917 165 545 102 999 106 991 499 540 958 773 831 315
 288 735 959 363 702 714 655 549] [195 672 139 181 162 431 523  51 802 589 998 352 180 628 183 768 766 503
 618 116 320 326 942 271 806 737 484 600  75  61 846 150 797 381 951 205
 274  80 149 742 234 378 118 729 408 969 723 275 971  99 952 203 563 420
 134 354   0 914 820 344 829   8 974  21 967 801 356 189 808 141 279 616
 542 392 972 442 173 448 694 691 146 226 707 244 169 794 858 926 369 283
 556 389 367 210 739 395 676 534  72 316 124 887 456 498 692 206 661 818
 437 175 394 306 114 384 468  40  42 350 104 196 137 596 302 927 190 953

In [72]:
cross=cross_validate(LogisticRegression(),features,target,scoring='accuracy',cv=shuf_split,return_train_score=True)
cross

{'fit_time': array([0.16781163, 0.14561915, 0.11909604, 0.08551717, 0.09210873,
        0.10064054, 0.16437674, 0.14400387, 0.13213682, 0.15328526]),
 'score_time': array([0.01022792, 0.01646662, 0.01527786, 0.01127195, 0.00937438,
        0.01076531, 0.02854276, 0.00886965, 0.01893902, 0.01388335]),
 'test_score': array([0.9  , 0.905, 0.885, 0.96 , 0.875, 0.955, 0.925, 0.975, 0.955,
        0.955]),
 'train_score': array([0.89875, 0.905  , 0.89875, 0.95125, 0.89875, 0.97375, 0.90875,
        0.97   , 0.95125, 0.97125])}

In [73]:
cross= cross_validate(LogisticRegression(),features,target,scoring='accuracy',cv=shuf_split,return_train_score=True)

test_acc=cross['test_score'].mean().round(2)

train_acc= cross['train_score'].mean().round(2)

print('Training_Acc:',train_acc,',','Testing_Acc:',test_acc)

Training_Acc: 0.93 , Testing_Acc: 0.93

##Stratified Shuffle Split

In [74]:
str_shuffle=StratifiedShuffleSplit(n_splits=10,test_size=0.2,random_state=50)
cross= cross_validate(LogisticRegression(),features,target,scoring='accuracy',cv=shuf_split,return_train_score=True)

test_acc=cross['test_score'].mean().round(2)

train_acc= cross['train_score'].mean().round(2)

print('Training_Acc:',train_acc,',','Testing_Acc:',test_acc)

Training_Acc: 0.93 , Testing_Acc: 0.93

KFold

In [75]:
kfold= KFold(n_splits=10,shuffle=True,random_state=50)

cross= cross_validate(LogisticRegression(),features,target,scoring='accuracy',cv=kfold,return_train_score=True)

test_acc=cross['test_score'].mean().round(2)

train_acc= cross['train_score'].mean().round(2)

print('Training_Acc:',train_acc,',','Testing_Acc:',test_acc)

Training_Acc: 0.95 , Testing_Acc: 0.94

In [76]:
cross= cross_validate(LogisticRegression(),features,target,scoring='accuracy',cv=10,return_train_score=True)

test_acc=cross['test_score'].mean().round(2)

train_acc= cross['train_score'].mean().round(2)

print('Training_Acc:',train_acc,',','Testing_Acc:',test_acc)

Training_Acc: 0.94 , Testing_Acc: 0.94

In [78]:
from sklearn.linear_model import LogisticRegressionCV

In [80]:
log_cv=LogisticRegressionCV(cv=5)
log_cv.fit(x_train,y_train)

LogisticRegressionCV(cv=5)

In [81]:
log_cv= LogisticRegressionCV(cv=5)

log_cv.fit(x_train,y_train)

y_pred= log_cv.predict(x_train)

train_acc= accuracy_score(y_train,y_pred)

y_pred1= log_cv.predict(x_test)

test_acc= accuracy_score(y_test,y_pred1)

print('Training_Acc:',train_acc,',','Testing_Acc:',test_acc)

Training_Acc: 0.9675 , Testing_Acc: 0.975