In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [2]:
df= pd.read_csv('sl1.csv')

In [3]:
df.shape

(5, 2)

In [4]:
df

   Area   Price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [5]:
target= df[['Price']]
features= df.drop(columns=['Price'])

In [34]:
x_train,x_test,y_train,y_test=train_test_split(features,target,train_size=0.7,random_state=10)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(3, 1)
(2, 1)
(3, 1)
(2, 1)

In [37]:
##### Model Training
lin_reg=LinearRegression()
lin_reg.fit(x_train,y_train)

LinearRegression()

In [40]:
b1=lin_reg.coef_
b1

array([[131.73076923]])

In [42]:
b0=lin_reg.intercept_
b0

array([191794.87179487])

In [43]:
x_train

   Area
0  2600
4  4000
1  3000

In [46]:
b1*3000+b0

array([[586987.17948718]])

In [50]:
y_pred=lin_reg.predict(x_train)
y_pred

array([[534294.87179487],
       [718717.94871795],
       [586987.17948718]])

In [52]:
#### Training Validation
r2_score(y_train,y_pred)

0.9591026776589222

In [53]:
#### Testing Validation
y_pred1=lin_reg.predict(x_test)
y_pred1

array([[613333.33333333],
       [666025.64102564]])

In [55]:
#### Testing Validation
r2_score(y_test,y_pred1)

0.9157576245488329